build/build.sh, build/push
=> chore(build): add license in build scripts

cmd/cvc-operator/main.go, go.mod, go.sum, pkg/controllers/cstorvolumeclaim/controller.go, pkg/controllers/cstorvolumeclaim/start.go, vendor/github.com/openebs/api/pkg/kubernetes/leaderelection/leader_election.go
=> feat(cvc): use openebs/api lease apis for leaderelection

cmd/cspc-operator/app/start.go
This commit uses lease apis to enable leader election in cspc-operator
=> feat(cspc-operator): use lease apis to enable leader election

Makefile, build/build.sh, build/cspc-operator/Dockerfile, build/pool-manager/Dockerfile, build/pool-manager/entrypoint.sh, build/volume-manager/Dockerfile, build/volume-manager/Dockerfile.arm64, build/volume-manager/entrypoint.sh
=> feat(build): add makefile tagets and Dockerfiles for all controllers

Makefile, build/pool-manager/Dockerfile, build/pool-manager/entrypoint.sh, build/volume-manager/Dockerfile, build/volume-manager/entrypoint.sh
=> fix(dockerfile): use updated binary names for pool and volume manger

.github/workflows/go.yml, pkg/controllers/volume-mgmt/volume/volume.go, pkg/controllers/volume-mgmt/volume/volume_test.go, pkg/signals/signal_posix.go, pkg/volume-rpc/client/api.go, pkg/volumereplica/volumereplica_test.go
=> feat(build): add github actions to run test and build

Makefile, build/cstor-webhook/Dockerfile
This PR adds makefile and Dockerfile for building cstor webhook image.
=> feat(build): add makefile target and Dockerfile for cstor webhook

go.mod, go.sum, pkg/controllers/cspc-controller/cleanup.go, pkg/controllers/cspc-controller/operations.go, pkg/cspc/algorithm/select_node.go, pkg/cspc/algorithm/select_node_test.go, pkg/pool/operations/create.go, pkg/pool/operations/delete.go, pkg/pool/operations/disk_operation.go, pkg/pool/operations/import.go, pkg/pool/operations/modify.go, pkg/pool/operations/pool_utils.go, pkg/webhook/bd_replacement.go, pkg/webhook/bd_replacement_test.go, pkg/webhook/cspc.go, pkg/webhook/cspc_test.go
This PR updates the code to use updated APIs.
=> chore(cstor_pool_apis): update code to use updated cStor pool APIs

go.mod, go.sum, pkg/controllers/cspc-controller/sync.go, pkg/cspc/algorithm/build_csp.go, pkg/cspc/algorithm/build_deploy.go, pkg/cspc/algorithm/select_node.go, vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolcluster.go, vendor/github.com/openebs/api/pkg/apis/cstor/v1/zz_generated.deepcopy.go, vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/cstorpoolcluster.go, vendor/github.com/openebs/api/pkg/internalapis/apis/cstor/zz_generated.deepcopy.go, vendor/modules.txt
This PR adds functionality to reconcile for cspc tunables.
=> feat(cspc): add reconciliation for cspc tunables

pkg/controllers/cspc-controller/status.go, pkg/controllers/cspc-controller/util/cspc_util.go, pkg/controllers/cspc-controller/util/cspc_util_test.go
This PR adds constants for cspc condition reason
=> refact(cspc): add tests and constants for cspc conditions

.github/workflows/go.yml, Makefile
=> fix(ci): refactor github actions and Makefile targets

pkg/webhook/configuration.go
=> refact(webhook): update the admission service and config name

Makefile
Changes:
- Updating makefile target `deps` to check if go modules file are updated or not
Signed-off-by: mayank <mayank.patel@mayadata.io>
=> refact(build): updating makefile to verify go mod files

.travis.yml, ci/sanity/install.sh, ci/sanity/sanity.sh
=> chore(ci): fast fail travis script in case of error

pkg/controllers/cstorvolumeconfig/volume_operations.go
This PR is cherry-pick of PR [68](https://github.com/openebs/cstor-operators/pull/68).
=> cherry-pick(log): add more information in error event (#68)

pkg/pool/operations/pool_utils.go
This PR removes the CSPC finalizer on blockdeviceclaim of blockdevice once a replacement is successful.
**NOTE:**
This issue will happen only when the blockdevice was replaced.
=> fix(cspi): remove finalizer on claim of blockdevice which underwent replacement

pkg/pool/operations/pool_utils.go
This PR is cherry-pick PR of [71](https://github.com/openebs/cstor-operators/pull/71).
** What This PR Does**:
This PR removes the CSPC finalizer on blockdeviceclaim of blockdevice once a replacement is successful.
=> cherry-pick(fix): remove finalizer on claim of blockdevice which underwent replacement

ci/sanity/sanity.sh, go.mod, go.sum, pkg/pool/operations/import.go, vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolcluster.go, vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/blockdeviceclaimbuilder.go, vendor/github.com/openebs/api/pkg/apis/types/types.go, vendor/modules.txt
This PR is the cherry-pick of PR https://github.com/openebs/cstor-operators/pull/77
=> cherry-pick(cspi): import pool without cachefile

pkg/controllers/cstorvolumeconfig/volume_operations.go
=> fix(cvc): change cvr capacity to provisioned capacity (#90)

pkg/controllers/common/common.go, pkg/controllers/replica-controller/handler.go, pkg/controllers/restore-controller/handler.go, pkg/controllers/restore-controller/new_restore_controller.go
This PR is a cherry-pick of the following PR
https://github.com/openebs/cstor-operators/pull/92
=> Cherry pick of pr #92

pkg/webhook/cspc.go
This PR cherry-picks the PR #94 to v1.11.x branch.
=> fix(webhook): check for hostname instead of nodename for bd validations (#94)

docs/tutorial/intro.md, docs/tutorial/volumes/migration.md, docs/tutorial/volumes/resize.md, docs/tutorial/volumes/snapshot.md, docs/tutorial/volumes/volume.md
=> chore(docs): add cstor csi volume feature related docs

pkg/version/util.go
This PR is cherry-pick for https://github.com/openebs/cstor-operators/pull/120
=> fix(version): split version string to segregate version from tags

pkg/controllers/cstorvolumeconfig/controller_base.go, pkg/controllers/cstorvolumeconfig/controller_test.go
=> chore(cvc): add cvc-controller fake client mock tests

pkg/controllers/cspi-controller/handler_test.go, pkg/webhook/cspc.go, pkg/webhook/cspc_test.go
This PR adds unit test for pool provisioning with more different count of block devices per raid group.
=> test(unit test): add test cases for cstor pool provisioning

pkg/webhook/cspc.go
This is a cherry-pick of PR
https://github.com/openebs/cstor-operators/pull/122
=> cherrypick(#122): fixes pool scaledown bug

docs/developer-guide/devel.md, docs/developer-guide/start.md, docs/quick.md
A small update to the documentation.
- reflect go-module support in developer guide
- fix slack link
- update csi-operators yaml file links.
Signed-off-by: vaniisgh <vanisingh@live.co.uk>
=> Update docs for setup & quickstart

CHANGELOG.md
=> chore(changelog): add 1.12.0 release CHANGELOG

docs/tutorial/cspc/tuning/tune.md, docs/tutorial/intro.md
This PR adds CSPC tuneables docs.
=> chore(docs): add cspc tunables docs

README.md, docs/developer-guide/cstor-pool-docs.md, docs/developer-guide/cstor-pool.md
This PR adds cStor pool resource organization docs.
**Note To Reviewers:**
Once the docs for cStor volume resource organization is done, a link will be supplied in this doc.
=> chore(docs): add cStor pool resource organization docs

docs/tutorial/volumes/policy.md
=> chore(docs): add volume policy docs with example configurations

README.md, docs/troubleshooting/pool_operations_hung.md, docs/troubleshooting/troubleshooting.md, docs/tutorial/intro.md
Add troubleshooting document for recovering from stuck pool pod.
=> docs(bad_disk): add troubleshooting document to recover stuck pool pod

README.md, docs/developer-guide/cstor-pool.md, docs/developer-guide/cstor-volume.md
=> docs(cstorvolume): add cStor volume resource organisation document.

docs/tutorial/intro.md, docs/tutorial/volumes/block_volume.md
=> docs(volume): add raw block volume docs with a usecase

pkg/version/util.go
This PR cherry-picks the PR #152
=> chore(version): update upgrade matrix with valid current versions

deploy/crds/all_cstor_crds.yaml, deploy/csi-operator.yaml, go.mod, go.sum, vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolinstance.go, vendor/modules.txt
This PR is cherry-pick of PR #156 
=> cherry-pick(vendor): sync with openebs apis changes

README.md, docs/quick.md, docs/tutorial/cspc/tuning/tune.md, docs/tutorial/intro.md
=> chore(docs): update README and quick.md files 

CHANGELOG.md
=> chore(docs): add 2.0.0 release CHANGELOG

.github/workflows/go.yml, Makefile, pkg/controllers/cspc-controller/util/cspc_util_test.go, pkg/controllers/cstorvolumeconfig/volume_operations_test.go, pkg/snapshot/snapshottest/snapshot.go, pkg/version/util.go, pkg/volume-rpc/targetserver/config.go, pkg/zcmd/zfs/stats/stats.go, tests/cstorvolume/provisioing/provisioning_utils.go
This PR adds license check in CI
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
=> chore(ci): add license check in ci

.github/workflows/go.yml, Makefile, build/cspc-operator/Dockerfile, build/cstor-webhook/Dockerfile, build/cvc-operator/Dockerfile, build/cvc-operator/Dockerfile.arm64, build/cvc-operator/entrypoint.sh, build/pool-manager/Dockerfile, build/pool-manager/entrypoint.sh, build/volume-manager/Dockerfile, build/volume-manager/Dockerfile.arm64, build/volume-manager/entrypoint.sh
This PR adds license check for for .sh and Dockerfile
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
=> chore(license): add license check for .sh and Dockerfile

pkg/version/util.go
=> chore(upgrade): add valid current versions for 2.1.0 upgrades

CHANGELOG.md
=> chore(changelog) : add changelog for 2.1.0

deploy/csi-operator.yaml, docs/tutorial/intro.md, docs/tutorial/volumes/prometheus-monitoring.md
- add csi cstor volume metrics exposed by prometheus
- Bump csi snapshotter to v2.1.1 having some good fixes
- Include google analytics changes 
=> chore(docs): add csi cstor volume metrics exposed by prometheus

README.md
Hello,
As message title says.
Didier
Signed-off-by: didier <durand.didier@gmail.com>
=> fix various language issues on homepage

docs/tutorial/cspc/allow-tagged-bds/allowed-bds.md, docs/tutorial/intro.md
=> docs(bd-tag): add tutorial for using BD tag feature.

deploy/crds/all_cstor_crds.yaml
- update backup and restore crds description
- add upgradetasks crd all_crd_yaml
=> refact(crds): update crds based on new api spec changes

pkg/server/cstorvolumeconfig/backup_endpoint.go, pkg/server/cstorvolumeconfig/https_test.go, pkg/server/cstorvolumeconfig/restore_endpoint.go
This PR is cherry-pick of #192 
=> cherry-pick[fix, backup, restore]: create backup and restore in cstor.openebs.io/v1 group

CHANGELOG.md
=> chore(changelog): add changelog for 2.2.0 RC1

deploy/crds/all_cstor_crds.yaml, deploy/ndm-operator.yaml
- Bump NDM version 0.9.1
- Update crds to use v1 version
=> refact(crds): update crds to use apiextensions.k8s.io/v1 apis

CHANGELOG.md, changelogs/released/v2.3.0-RC1/155-shubham14bajpai, changelogs/released/v2.3.0-RC1/187-prateekpandey14, changelogs/released/v2.3.0-RC1/197-prateekpandey14, changelogs/released/v2.3.0-RC1/198-zlymeda, changelogs/released/v2.3.0-RC1/205-daximillian
This PR adds changelog for v2.3.0
=> chore(CHANGELOG): add changelogs for v2.3.0

pkg/version/util.go
This PR adds 2.4.1 to the upgrade matrix
=> chore(version): add 2.4.1 to upgrade matrix

.github/workflows/build.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, pkg/version/util.go
This PR updates the buildx action version to the latest stable release. This PR also updates the upgrade matrix with 2.5.0.
=> chore(build): update the buildx action verison

go.mod, go.sum, pkg/controllers/cstorvolumeconfig/deployment.go, pkg/cspc/algorithm/build_deploy.go, vendor/github.com/openebs/api/v2/pkg/kubernetes/core/pod.go, vendor/github.com/openebs/api/v2/pkg/kubernetes/core/secret.go, vendor/github.com/openebs/api/v2/pkg/util/env.go, vendor/modules.txt
- add image pull secrets via the env `OPENEBS_IO_IMAGE_PULL_SECRETS` to pool and volume deployment
=> feat(pool, volume): add image pull secrets to pool and volume deployment

go.mod, go.sum, pkg/controllers/cstorvolumeconfig/deployment.go, pkg/cspc/algorithm/build_deploy.go, vendor/github.com/openebs/api/v2/pkg/kubernetes/core/pod.go, vendor/github.com/openebs/api/v2/pkg/kubernetes/core/secret.go, vendor/github.com/openebs/api/v2/pkg/util/env.go, vendor/modules.txt
* add a method to get image pull secrets from env
* add image pull secrets to pool and volume pods
cherry-pick #225
=> feat(pool, volume): add image pull secrets to pool and volume pods

docs/tutorial/intro.md, docs/tutorial/volumes/storageclass.md
=> chore(docs):add topology aware storageclass docs and example

Makefile.buildx.mk
=> fix(action): fix cstor pool and volume manager image names

index.md
- add helm upgrade steps into helm repo webpage
=> doc(website): add helm upgrade steps into helm repo

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/crds/volumesnapshot.yaml, deploy/helm/charts/crds/volumesnapshotclass.yaml, deploy/helm/charts/crds/volumesnapshotcontent.yaml, deploy/helm/charts/templates/csi-controller-rbac.yaml, deploy/helm/charts/templates/csi-controller.yaml, deploy/helm/charts/templates/cspc-operator.yaml, deploy/helm/charts/templates/cvc-operator.yaml, deploy/helm/charts/templates/snapshot-class.yaml, deploy/helm/charts/values.yaml
- update chart version and dependency version
- update README
- update values.yaml
- update snapshot CRDs
- update cspc operator and cvc operator deployment
- update csi-controller
- update csi-controller-rbac
Documentation update in #230 
=> [stable/cstor]: update cstor charts to 2.5.0

index.md
Fixes #232 
Signed-off-by: Sebastien Dionne <survivant00@gmail.com>
=> fix issue : 232

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md
- update chart version and dependency version
- update README
To be merged after : https://github.com/openebs/node-disk-manager/pull/535
=> [stable/cstor]: update dependent NDM charts to 1.1.1

pkg/version/util.go, pkg/webhook/cspc.go
=> fix(webhook): allow cspc validation based on supported compression algos

pkg/webhook/namespace.go
=> refact(webhook): refactor namespace validation steps

pkg/webhook/configuration.go, pkg/webhook/namespace.go, pkg/webhook/util.go, pkg/webhook/webhook.go
=> fix(webhook): cleanup validatingconfig on openebs namespace deletion 

index.md
This PR adds the configurable flags and dependencies information to the index.md
=> chore(charts): add configurable flags and dependencies to index.md

.github/workflows/pull_request.yml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/templates/csi-node-rbac.yaml, deploy/helm/charts/templates/csi-node.yaml, deploy/helm/charts/templates/psp.yaml
=> refact(charts): add pod security policy for cstor charts

.github/workflows/chart-lint-test.yml, ct.yaml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/crds/cstorvolumeattachment.yaml, deploy/helm/charts/crds/upgradetask.yaml, deploy/helm/charts/templates/cleanup-webhook.yaml, deploy/helm/charts/templates/csi-node.yaml, deploy/helm/charts/values.yaml
- update chart version
- update dependent chart version
- update README
- update values.yaml
Dependent on openebs/node-disk-manager#540
=> [stable/cstor]: update charts to 2.6.0

CHANGELOG.md
=> chore(changelog): add v2.6.0 changelogs

docs/quick.md
=> chore(docs): add helm charts in install instructions

ci/sanity/sanity.sh, deploy/ndm-operator.yaml
=> fix(ci): increase timeout values for pool checks and update ndm operator

docs/quick.md
=> chore(docs): Trim cStor quickstart

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, docs/quick.md
Adding installation instructions for microk8s.
This will only work after https://github.com/openebs/charts/pull/209 is merged.
=> chore(docs): add instructions for microk8s

pkg/webhook/configuration.go
**What this PR does?**:
Add admissionReviewVersions as `v1` version since its a required value to be populated with v1 admission apis in k8s 1.20+ release onwards.
**Does this PR require any upgrade changes?**:
Yes, upgrade has been handled internally
=> fix(webhook): populate admissionReviewVersions as a required value

Makefile, pkg/webhook/webhook.go
=> fix(webhook): fix admission review response order

Makefile, pkg/webhook/webhook.go
=> fix(webhook): fix admission review response apis (#275)

docs/tutorial/volumes/snapshot.md
=> chore(docs): Fix typo

CHANGELOG.md, changelogs/released/v2.8.0-RC1/263-niladrih, changelogs/released/v2.8.0-RC1/267-prateekpandey14, changelogs/released/v2.8.0-RC1/270-shubham14bajpai, changelogs/released/v2.8.0-RC1/273-prateekpandey14, changelogs/released/v2.8.0-RC1/275-prateekpandey14
=> chore(docs): add v2.8.0 release changelogs

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
- update chart version
- update NDM dependency version 1.4.0
- update README
- update values.yaml
Note: restart the chart builds once the NDM charts PR merged
=> [stable/cstor]: update cstor charts to 2.8.0

cmd/volume-manager/app/commands.go
=> Remove Unused snapName fieldname

cmd/volume-manager/app/commands.go, cmd/webhook/main.go, pkg/controllers/cspc-controller/handler_test.go, pkg/controllers/cspi-controller/handler_test.go, pkg/controllers/cstorvolumeconfig/controller_base.go, pkg/controllers/cstorvolumeconfig/controller_test.go, pkg/controllers/cstorvolumeconfig/deployment.go, pkg/controllers/cstorvolumeconfig/start.go, pkg/controllers/testutil/zcmd/zpool/set.go, pkg/controllers/volume-mgmt/controller.go, pkg/controllers/volume-mgmt/volume/volume_test.go, pkg/cspc/algorithm/config.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
=> (bugsbash)remove unused code

cmd/webhook/main.go
=> remove unused  fieldname masterurl

pkg/controllers/cspc-controller/handler_test.go
=> Remove unused function

pkg/controllers/cspi-controller/handler_test.go
=> Remove unused ignoreActionExpectations field

pkg/controllers/backup-controller/controller.go, pkg/controllers/backup-controller/handler.go
Signed-off-by: aSquare14 <atibhi.a@gmail.com>
=> (bugsbash) fix return statements

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
=> [stable/cstor]: update cstor charts to 2.9.0 release

pkg/cspc/algorithm/config.go, pkg/cspc/algorithm/select_node_test.go, pkg/pool/pool.go, pkg/signals/signal.go, pkg/webhook/webhook.go
=> Remove unused code

pkg/controllers/common/common_test.go, pkg/controllers/cspi-controller/handler.go, pkg/controllers/replica-controller/runner_test.go, pkg/server/cstorvolumeconfig/backup_endpoint.go
=> Remove unused usage of ftm

pkg/zcmd/zpool/attach/builder.go, pkg/zcmd/zpool/destroy/builder.go, pkg/zcmd/zpool/export/builder.go
=> Remove usage of fmt.sprintf

pkg/controllers/cspc-controller/scale.go, pkg/controllers/cspc-controller/sync.go, pkg/controllers/cspi-controller/handler_test.go, pkg/controllers/cstorvolumeconfig/controller.go, pkg/pool/operations/disk_operation.go, pkg/server/cstorvolumeconfig/restore_endpoint.go, pkg/webhook/cspc_operations.go, pkg/webhook/cvc.go, pkg/zcmd/zfs/listsnap/builder.go
Signed-off-by: Sreehari Mohan <sreeharimohan11@gmail.com>
All superfluous err nil checks in the pkg folder have been changed.
This does not affect any of the functionalities. It just cleans up unneeded code and reduces the complexity of the functions involved.
=> fixed all opt.semgrep.err-nil-check issues

ci/sanity/install.sh, ci/sanity/sanity.sh
=>  Move usr/bin declaration to top of file 

pkg/version/util.go
This PR adds the version 2.10.0 to upgrade matrix
=> chore(version): add 2.10.0 to upgrade matrix

CONTRIBUTING.md, README.md
=> refact(docs): update Project README and contributors docs

pkg/webhook/util.go, pkg/webhook/util_test.go
=> fix(webhook): fix version comparison of webhook resources

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/templates/cvc-operator.yaml, deploy/helm/charts/values.yaml
=> [stable/cstor]: update helm charts to 2.10.0 release

changelogs/unreleased/349-prateekpandey14, go.mod, go.sum, pkg/controllers/replica-controller/controller.go, pkg/controllers/replica-controller/handler.go, pkg/controllers/replica-controller/runner.go, vendor/github.com/cespare/xxhash/LICENSE.txt, vendor/github.com/cespare/xxhash/README.md, vendor/github.com/cespare/xxhash/go.mod, vendor/github.com/cespare/xxhash/go.sum, vendor/github.com/cespare/xxhash/rotate.go, vendor/github.com/cespare/xxhash/rotate19.go, vendor/github.com/cespare/xxhash/xxhash.go, vendor/github.com/cespare/xxhash/xxhash_amd64.go, vendor/github.com/cespare/xxhash/xxhash_amd64.s, vendor/github.com/cespare/xxhash/xxhash_other.go, vendor/github.com/cespare/xxhash/xxhash_safe.go, vendor/github.com/cespare/xxhash/xxhash_unsafe.go, vendor/modules.txt
**What this PR does**
PR update CVR status to `offline` on graceful shutdown/termination of pool-manager pod/container deletion, eviction, scale down scenarios.
=> fix(status): update cvr status on graceful corresponding pool-manager termination

.github/workflows/build.yml
=> fix(workflow): fix ansible job action workflow

pkg/version/util.go
This PR Adds 2.11.0 to the upgrade matrix.
=> chore(version): add 2.11.0 to upgrade matrix

e2e-tests/Dockerfile, e2e-tests/experiments/cstor-operator/cspc-pool-provision/run_e2e_test.yml
- Included the dependent package to install the pip openshift for ansible docker file
=> refactor[e2e]: Included the dependent package for build the e2e image

CHANGELOG.md
=> chore(docs): add v2.11.0 release changelog

.github/workflows/chart-lint-test.yml, deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
=> [stable/cstor]: update cstor charts to 2.11.0 release

deploy/helm/charts/Chart.yaml, deploy/helm/charts/templates/snapshot-class.yaml
Update api version check cinclude kind along with apiversion.
=> update(helm): update api version check with helm capability

deploy/ndm-operator.yaml
=> chore(operator): sync NDM operator with latest changes

pkg/controllers/cspc-controller/sync.go
=> fix(cspc): fix cspc operator sync logs

e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/test_vars.yml
- Updated the test case name for multiple application login request on single cstor csi volume infra chaos test case to create the test results CR
=> fix[e2e]: Updated the test name for multiple application login request infra chaos test

deploy/helm/charts/Chart.yaml, deploy/helm/charts/README.md, deploy/helm/charts/values.yaml
=> [stable/cstor]: update cstor charts to 2.12.0 release

e2e-tests/experiments/cstor-operator/cstor-operator-provisioner/test_vars.yml
- This PR updates the changes made in the openebs/charts repo as part of this PR `https://github.com/openebs/charts/pull/255`
=> refactor[e2e]: Updated the path for the cstor operator yaml
