openebs/cstor-operators

- cmd/webhook/main.go
- pkg/webhook/admission_response.go
- pkg/webhook/bd_replacement.go
- pkg/webhook/bd_replacement_test.go
- pkg/webhook/configuration.go
- pkg/webhook/cspc.go
- pkg/webhook/cspc_test.go
- pkg/webhook/cvc.go
- pkg/webhook/cvc_test.go
- pkg/webhook/doc.go
- pkg/webhook/pvc.go
- pkg/webhook/triple.go
- pkg/webhook/util.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
This PR adds webhook server code to validate cstor related create, update and delete requests.
> feat(webhook): add cstor-webhook using openebs/api changes

- examples/crds/cspicrd.yaml
- examples/cspc/cspc-single.yaml
This PR 
- corrects the fields in poolConfig of example.
- adds `additionalPrinterColumns` for `CSPI` crd for proper status via kubectl get.
> fix(yaml): update poolConfig fields in examples

- pkg/webhook/configuration.go
- pkg/webhook/cspc.go
This PR
-  adds validation for new schema changes in CSPC. 
-  reverts the API version of `ValidatingWebhookConfig` to v1beta1 as the `sideEffectClass` `NoneOnDryRun` does not seem to work in this case and v1 does not support `Unknown` class. Will look into it until then using v1beta1.
TODO:
- validation for expansion
- validation for capacity
will take these in separate PRs.
> refact(webhook): add validation for new fields in cspc

- Makefile
- pkg/controllers/cstorvolumeclaim/deployment.go
- pkg/controllers/cstorvolumeclaim/volume_operations.go
- pkg/cspc/algorithm/build_deploy.go
- fix volume provisioning due to stale error checks
- Rename `pool-manager` image to `cstor-pool-manager`
- rename `volume-manager` image to `cstor-volume-manager`
- Use `IfNotPresent` instead of `Always` pull container images in pool deployment.
> chore(cvc): refactor volume and pool provisioning including updated image names

- go.sum
- pkg/controllers/cspi-controller/handler.go
- pkg/cspc/algorithm/build_csp.go
- pkg/pool/operations/status.go
- pkg/zcmd/zpool/get/builder.go
This PR adds support for ROThresholdLimit in the pool manager.
Note:
1. If `roThresholdLimit` is set to `0` or `100`:
-  Writes on the pool will be allowed until it runs out of space.
Sample CSPI spec and status when pool in RW state
```sh
poolConfig:
...
...
roThresholdLimit: 12
status:
Conditions: null
capacity:
free: 9470M
total: 9940M
used: 476M
phase: ""
readOnly: false
```
Sample CSPI spec and status when pool is in RO mode
```sh
poolConfig:
...
...
roThresholdLimit: 2
status:
Conditions: null
capacity:
free: 9470M
total: 9940M
used: 476M
phase: ""
readOnly: true
```
Events Generation:
```sh
I0312 18:00:30.985242   19525 event.go:281] Event(v1.ObjectReference{Kind:"CStorPoolInstance", Namespace:"openebs", Name:"cspi-stripe", …
```
> feat(roThresholdLimit): add ROThresholdLimit support in pool manager

- deploy/cstor-operator.yaml
- go.mod
- go.sum
- pkg/controllers/common/common_test.go
- pkg/controllers/cspc-controller/controller.go
- pkg/controllers/cspc-controller/handler.go
- pkg/controllers/cstorvolumeclaim/deployment.go
- pkg/cspc/algorithm/build_deploy.go
- pkg/cspc/algorithm/config.go
- pkg/pool/operations/pool.go
- pkg/pool/operations/pool_utils_test.go
- pkg/zcmd/cmd.go
- pkg/zcmd/zpool/dump/builder.go
defaults to service account `openebs-maya-operator` in case
not provided.
refer: depends on https://github.com/openebs/api/pull/28
> feat(operator): make openebs service account configurable for pool and volume deployments

- pkg/controllers/cspi-controller/handler.go
- pkg/pool/operations/modify.go
- pkg/pool/operations/status.go
This commit fixes the error handling bugs and ZPOOL
handling bugs.
```sh
kubectl get cspi -n openebs
NAME          HOSTNAME    ALLOCATED   FREE    CAPACITY   STATUS   AGE
cspi-stripe   127.0.0.1   69500       9940M   9940M      ONLINE   9m10s
```
> fix(cspi, status): fix CSPI status to represent capacity and Phase of pool

- pkg/controllers/cspi-controller/handler.go
- pkg/pool/operations/create.go
- pkg/pool/operations/pool_utils.go
This commit adds capability to set compression on the cstor pool. The
Compression can be set via cspc and value must be one of 'on | off | lzjb |
gzip | gzip-[1-9] | zle | lz4'.
Note: lz4 is the defualt compression algorithm that is used if the compression field is left unspecified on the cspc.
> feat(cspi): add capability to set compression on cstor pool

- pkg/pool/operations/create.go
- pkg/zcmd/zpool/create/builder.go
- pkg/zcmd/zpool/create/predicate.go
commit fixes the zpool create cmd with `compression` as a filesystem
property with `-O` which is failed due to `-o` used earlier
cmd example:
```sh 
zpool create -o cachefile=/var/openebs/cstor-poolpool.cache -O compression=lz4
cstor-b662a561-3c89-4eec-b6f0-a19ee12004a2 /var/openebs/sparse/4-ndm-sparse.img
```
> fix(cspi): pool create with compression as filesystem property

- pkg/controllers/cspc-controller/cleanup.go
- pkg/controllers/cspc-controller/cleanup_test.go
- pkg/controllers/cspc-controller/handler.go
- pkg/controllers/cspc-controller/sync.go
This PR does following enhancements:
1. If there is a mismatch b/w cspc and cspc-operator version the cspc
is not reconciled. If the cspc has an empty version then cspc is reconiled.
2. The cspc and cspi cleanup function is improved and test cases are added
with fakecontrollers.
> chore(cspc): refactor cspc reconcile and cleanup

- Makefile
This PR add amd64 in image name for images produced by cstor-operator repo.
Subsequent PRs that will be raised : 
1.  Change to propagate new image name in operator yaml or code -- wherever required
2. CI to push images to OpenEBS repository.
*NOTES:* Corresponding changes to code/operator yaml for the image name change needs to be propagated.
> chore(build): make image tags with amd64 for amd64 builds

- pkg/webhook/configuration.go
- pkg/webhook/cvc.go
- pkg/webhook/cvc_test.go
- pkg/webhook/webhook.go
- Adds validation for `cstorvolumeconfig` immutable fields
- Update `ValidatingWebhookConfiguration` apis rules to validate only `v1` APIs
- Adds `CstorVolumeConfigs` apis rules in `ValidatingWebhookConfiguration` to validate
Fixes: openebs/openebs/issues/3003
> feat(webhook): add volume specific webhook validations

- build/cspc-operator/Dockerfile
- build/cvc-operator/Dockerfile
- build/cvc-operator/Dockerfile.arm64
- build/pool-manager/Dockerfile
- build/volume-manager/Dockerfile
- build/volume-manager/Dockerfile.arm64
- deploy/cstor-operator.yaml
- deploy/ndm-operator.yaml
- deploy/rbac.yaml
- commit changes to use openebs-maya-operator service account for all cstor deployments.
- Add `openebs-cstor-operator` clusterRole and ClusterRolebindings to main `openebs-maya-operator ` service account
> fix(operator): use single service account for deployments

- pkg/controllers/cspc-controller/handler_test.go
- pkg/controllers/cspc-controller/sync.go
- pkg/controllers/testutil/test_utils.go
- pkg/cspc/algorithm/select_node.go
- pkg/pool/operations/create.go
This PR adds unit tests for following:
1. CSPC pool provisioning on single node [stripe,mirror,raidz and raidz2]
2. CSPC pool provisioning on 3 node [stripe,mirror,raidz and raidz2]
3. Pool scale up
4. Pool expansion [stripe,mirror,raidz and raidz2]
> chore(refactor) : add fake controller testing for cspc-operator

- pkg/webhook/cspc.go
- pkg/webhook/cspc_operations.go
- pkg/webhook/cspc_operations_test.go
- pkg/webhook/cspc_test.go
This PR adds webhook validations for cspc expansion.
Refer: https://github.com/openebs/maya/pull/1588
TODO:
add unit test for new functions
> feat(webhook): add cspc expansion validations

- Makefile
- build/cspc-operator/Dockerfile
- build/cstor-webhook/Dockerfile
- build/cvc-operator/Dockerfile
- build/cvc-operator/Dockerfile.arm64
- build/pool-manager/Dockerfile
- build/push
- build/volume-manager/Dockerfile
- build/volume-manager/Dockerfile.arm64
This PR does the following :
1. The container images should be pushed without a `v` in the tag SEMVER.
The refactors script to trims the leading `v` before pushing 
2. Change the env variable `HUB_USER` to `IMAGE_ORG` for consistency across openebs repos.
This variable holds the image repository user name.
3. Modifies the Dockerfiles to add the required labels.
> chore(push_script): refactor makefile and push scirpt

- Makefile
**What this PR does:**
The docker tags are created by removing the `v` from
prefix of TRAVIS_TAG (github tag). Using TRAVIS_TAG
to fetch cstor base image fails to build cstor related
containers.
> refact(build): fix cstor base image tag

- Makefile
commit update the trim expression in Makefile which is failing
with the error unterminated variable reference due to error
in parsing expression
Similar logic works in bash script but not in Makefiles
> fix(Makefile): update the expression to trim 'v' from tag

- pkg/controllers/cspc-controller/handler.go
- pkg/controllers/cspc-controller/sync.go
- pkg/controllers/cspi-controller/handler.go
- pkg/controllers/cspi-controller/volumereplica/handler.go
- pkg/controllers/cstorvolumeconfig/controller.go
- pkg/controllers/volume-mgmt/handler.go
This PR adds an upgrade framework for all the controllers to perform any upgrade steps from within the controller itself to avoid any pod exec issues.
> feat(upgrade): add upgrade framework in controllers

- pkg/controllers/cstorvolumeconfig/volume_operations.go
This PR adds the CPSC information in the error log. When the user Provision a volume with storage replciaCount > no.of available pools (or) when the user mentioned a typo of CSPC name then event will be shown.
> chore(log): add cspc information in error event

- ci/sanity/sanity.sh
- go.mod
- go.sum
- pkg/pool/operations/import.go
- vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolcluster.go
- vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/blockdeviceclaimbuilder.go
- vendor/github.com/openebs/api/pkg/apis/types/types.go
- vendor/modules.txt
This PR will try to import the pool without the cache file as a last option. 
It will import the pool in the following ways:
- Import the pool using cachefile  `zpool import -c cachefile=<cache_file> -o cachefile=<cache_file> <pool_name>`
- Import the pool without using cachefile:
1. If it is sparse based pool then command will be `zpool import  -o cachefile=<cache_file> -d <parent_directory_of_sparse_file> <pool_name>`
2. If it device based pool then command will be `zpool import -o cachefile=<cache_file> <pool_name>`(By default it will scan /dev directory).
**NOTE**:
- Due to bug in persisting the cachefile i.e cachefile is not stored in the persistent path because of this when pool pod got restarted then the pool will not be …
> fix(cspi): import pool without cachefile

- Makefile
- build/cspc-operator/Dockerfile
- build/cstor-webhook/Dockerfile
- build/cvc-operator/Dockerfile
- build/cvc-operator/Dockerfile.arm64
- build/pool-manager/Dockerfile
- build/volume-manager/Dockerfile
- build/volume-manager/Dockerfile.arm64
The forked repo might push the images to a
custom org that is set via IMAGE_ORG env.
Removed hardcoded references to org as 'openebs'
Also, removed duplicate docker labels.
Signed-off-by: kmova <kiran.mova@mayadata.io>
> refactor(build): remove hardcoded docker org

- Makefile
- build/cspc-operator/Dockerfile
- build/cstor-webhook/Dockerfile
- build/cvc-operator/Dockerfile
- build/cvc-operator/Dockerfile.arm64
- build/pool-manager/Dockerfile
- build/volume-manager/Dockerfile
- build/volume-manager/Dockerfile.arm64
The forked repo might push the images to a
custom org that is set via IMAGE_ORG env.
Removed hardcoded references to org as 'openebs'
Also, removed duplicate docker labels.
Signed-off-by: kmova <kiran.mova@mayadata.io>
(cherry picked from commit 3bfd267b44b03830ede065a9b31cd31079d4c5e9)
> refactor(build): remove hardcoded docker org (#84)

- pkg/webhook/cspc_operations.go
- pkg/webhook/cspc_test.go
This PR fixes the blockdevice replacement validations performed by the CStor admission server.
**Old RaidGroups**: RaidGroups of CSPC present in etcd.
**New RaidGroups**: RaidGroups of newly requested CSPC for updates.
**Before bug fix**:
- We are forming an index mapping(two different RaidGroup lists let us say rgList1 and rgList2. In these lists rgList1 of 0th index and rgList2 of 0th index contains the same RaidGroup[Marked RaidGroup as common which has at least one common blockdevice]) between old and new RaidGroups.
- Iterating over rgList1 and rgList2(as an outer and inner loop) and checking whether it is a case of replacement. If it a case of replacement then further [validations](https://github.com/openebs/openebs/blob/master/contribute/design/1.x/cstor-operator/doc.md#disk-replace …
> fix(webhook): fix blockdevice replacement validation

- cmd/pool-manager/app/start.go
- go.mod
- go.sum
- pkg/controllers/backup-controller/controller.go
- pkg/controllers/backup-controller/controller_test.go
- pkg/controllers/backup-controller/handler.go
- pkg/controllers/backup-controller/runner.go
- pkg/volumereplica/volumereplica.go
- vendor/github.com/openebs/api/pkg/apis/openebs.io/v1alpha1/register.go
- vendor/modules.txt
This PR adds the backup controller to the pool manager.
**Sample output**: kubectl describe -f backup.yaml 
```sh
Name:         snapshot2-pv-687c169c-4ec5-4144-9bcb-a30b75882c56
Namespace:    openebs
Labels:       cstorpoolinstance.openebs.io/name=cspc-stripe-hqqm
cstorpoolinstance.openebs.io/uid=bdf5571a-899c-4b30-ba23-7aecb9f3c49f
openebs.io/backup=backup2
openebs.io/persistent-volume=pv-687c169c-4ec5-4144-9bcb-a30b75882c56
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
{"apiVersion":"openebs.io/v1alpha1","kind":"CStorBackup","metadata":{"annotations":{},"creationTimestamp":"2020-06-02T15:01:04Z","generati...
API Version:  openebs.io/v1alpha1
Kind:         CStorBackup
Metadata:
Creation Timestamp:  2020-06-02T15:34:21Z
Generation:          4
Resource Version:    7605 …
```
> feat(backup-controller): add suport for backup controller

- pkg/controllers/cstorvolumeconfig/controller.go
- pkg/controllers/cstorvolumeconfig/volume_operations.go
This PR 
- comments out the check for `nodeID` to allow newly created CVC to reconcile for a migrated volume.
- adds code to honour the replica distribution for pool names mentioned in the CVC spec.
> refact(cvc-operator): update cvc controller for migration

- pkg/controllers/cstorvolumeconfig/volume_operations.go
This PR changes the cvr capacity to the cvc provisioned capacity to avoid any inconsistency when a resized volume is migrated to csi. This will ensure there is no inconsistency in cvrs or snapshots.
> fix(cvc): change cvr capacity to provisioned capacity

- pkg/webhook/cspc.go
This PR fixes the validateBlockdevice check for block devices in the webhook. This case occurs in clusters like EKS where the nodename and hostname label are different.
```sh
mayadata:setup$ kubectl get nodes --show-labels 
NAME                                           STATUS   ROLES    AGE   VERSION   LABELS
ip-192-168-14-68.us-east-2.compute.internal    Ready    <none>   36m   v1.15.9   alpha.eksctl.io/cluster-name=shubham-bajpai-eks,alpha.eksctl.io/instance-id=i-07d31cc59d39279e4,alpha.eksctl.io/nodegroup-name=standard-workers,beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=t3.large,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=us-east-2,failure-domain.beta.kubernetes.io/zone=us-east-2c,kubernetes …
```
> fix(webhook): check for hostname instead of nodename for bd validations

- deploy/rbac.yaml
This PR adds rbac rules for support of snapshot migration.
> chore(migration): add rbac rules for snapshot migration

- pkg/controllers/cstorvolumeconfig/deployment.go
commit enhances the cstorvolumepolicy to use any key:value pair
as a target podAffinity set in target deployment while provisioning and
scheduling
Below is the example to use policy to configure the affinity and other
policies
```
apiVersion: cstor.openebs.io/v1
kind: CStorVolumePolicy
metadata:
name: csi-volume-policy
namespace: openebs
spec:
provision:
replicaAffinity: true
replica:
zvolWorkers: ""
target:
resources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
auxResources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
tolerations:
- key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
priorityClassName: "system-cluster-critical"
affinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector: …
```
> feat(cvc): user policy based target podAffinity for target deployment

- .travis.yml
- pkg/webhook/cspc.go
- pkg/webhook/cspc_test.go
This PR adds cspc scale down validations. The webhook validates scale down by looking for any CVR exists on the scaled-down pool.
> feat(webhook): add cspc scaledown validations

- build/build.sh
- pkg/controllers/cstorvolumeconfig/controller.go
This PR does the following changes:
- Omits the VERSION file generation.
- Populates the current and desired version details for CVC if it is empty.
VERSION can have the following possible values:
- If Travis_TAG is set then `TRAVIS_TAG` then corresponding
tag will be the value.
- If TRAVIS_TAG is not set then the value will be  `${branch_name}-dev`
**Why we need this PR**:
This PR will populate the value of `openebs.io/version` and internal
resource version details based on build tag and build branch.
**Special Note To Reviewers**:
- VERSION value will be set on internal resources created by CVC and CSPC operators.
- This PR is continuation of #104 
> fix(VERSION): omit generation of VERSION file

- go.mod
- go.sum
- pkg/controllers/cstorvolumeconfig/volume_operations.go
- vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorvolumebuilder.go
- vendor/modules.txt
**What this change does **
PR initialize the CVR zvolworkers tunnables based on the given policy created  by the user
below is the example policy to configure different cstor tunnables 
```yaml
apiVersion: cstor.openebs.io/v1
kind: CStorVolumePolicy
metadata:
name: csi-volume-policy
namespace: openebs
spec:
provision:
replicaAffinity: true
replica:
zvolWorkers: "6"
target:
luWorkers: 8
queueDepth: "16"
resources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
auxResources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
.
.
.
```
> refact(cvp): initialize cvr zvolworkers based on policy

- deploy/cstor-operator.yaml
- pkg/webhook/configuration.go
**What this PR does?:**
commit enable the webhook validatingwebhookconfiguration failure policy configurable using a env called
ADMISSION_WEBHOOK_FAILURE_POLICY.
There are 2 types of failure policy which can be configurable are `Fail` and `Ignore`. `Fail` will be the default policy
**Does this PR require any upgrade changes?**:
NO
**If the changes in this PR are manually verified, list down the scenarios covered:**:
- deployed the admission server using `ignore` failure policy and verified that it got configured properly
> refact(webhook): make webhook config failure policy configurable

- pkg/controllers/cstorvolumeconfig/deployment.go
commit enhances the cstorvolumepolicy to use any key:value pair
as a target podAffinity set in target deployment while provisioning and
scheduling
Below is the example to use policy to configure the affinity and other
policies
```
apiVersion: cstor.openebs.io/v1
kind: CStorVolumePolicy
metadata:
name: csi-volume-policy
namespace: openebs
spec:
provision:
replicaAffinity: true
replica:
zvolWorkers: ""
target:
resources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
auxResources:
requests:
memory: "64Mi"
cpu: "250m"
limits:
memory: "128Mi"
cpu: "500m"
tolerations:
- key: "key1"
operator: "Equal"
value: "value1"
effect: "NoSchedule"
priorityClassName: "system-cluster-critical"
affinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector: …
```
> feat(cvc): user policy based target podAffinity for target deployment (#107)

- pkg/version/util.go
This PR fixes the version check for valid desired version which needs to be split from the tags in the version string. Example: 1.11.0-RC1 needs to split and 1.11.0 is the actual version.
> fix(version): split version string to segregate version from tags

- pkg/server/cstorvolumeconfig/https_test.go
- pkg/server/cstorvolumeconfig/restore_endpoint.go
This PR adds a mock test(unit test) for `Restore` endpoint.
_List of unit test_
**Backup endpoint**
- Trigger delete method on the backup endpoint(It should delete snapshot, CStorBackup, and CStorCompletedBackup CR's).
- Trigger delete method on the backup endpoint by injecting errors in snapshot deletion(should return an error).
- Trigger delete method on the backup endpoint when the backup is for scheduled backup(It should not delete CStorCompletedBackup).
- Trigger delete method on the backup endpoint without the required information(should return an error).
**Restore endpoint**
- Trigger POST method for remote restore on the restore endpoint(It should create required resources for restore).
- Trigger POST method for remote …
> test(restore): add mock test for restore endpoint

- pkg/webhook/cspc.go
In case of scaling down a pool by removing a pool spec from the CSPC, the webhook server was reporting an out of bounds error. This commit fixes this bug.
**Bug Description:**  
The validation code, in case of scaledown, was trying to list CSPI based on all the labels present on the nodes of the corresponding CSPI. On the other hand, CSPI only has `kubernetes.io/hostname` label to it and not all the other node labels. As labels are ANDed for output, we were not getting any items in the CSPI list and hence out of bounds error was caused.
> fix(cstor-webhook): fixes pool scaledown bug

- pkg/controllers/cstorvolumeconfig/deployment.go
- pkg/controllers/cstorvolumeconfig/volume_operations.go
commit add the PersistentVolumeClaim label `openebs.io/persistent-volume-claim` in volume target
deployments while volume provisioning
```sh
k get deploy pvc-52b679e8-b7c0-4efa-a98a-48aa17796e9b-target --show-labels
NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE   LABELS
pvc-52b679e8-b7c0-4efa-a98a-48aa17796e9b-target   1/1     1            1           70m   app=cstor-volume-manager,openebs.io/cas-type=cstor,openebs.io/persistent-volume-claim=claim-csi-123,openebs.io/persistent-volume=pvc-52b679e8-b7c0-4efa-a98a-48aa17796e9b,openebs.io/storage-engine-type=cstor,openebs.io/target=cstor-target,openebs.io/version=master-dev
```
> refact(cvc): add pvc label in volume target deployments

- pkg/webhook/cspc_operations.go
- pkg/webhook/cspc_test.go
**What does this PR does**:
In case of scaling down a pool by removing a pool spec
from the CSPC when a pool spec node doesn't exist in
the cluster, the cStor-admission server reported an error
saying no node exists for a given node selector. This PR
fixes this bug.
**Bug Description**:
- To validate day-2-operations(pool expansion, blockdevice replacement)
performed on the pool it was trying to get common pool specs from old
CSPC spec(CSPC exist in etcd) and new CSPC spec(modified CSPC
which needs to persist in etcd). common pool specs were figured out
by fetching hostName from node resource(node resource will be fetched
from etcd using nodeSelector on pool specs). In node doesn't exist
in the cluster then scaling down operation will be failed.
**Issue fixed by this PR** : …
> fix(cstor-webhook): allow scale down of pools when node doesn't exist in cluster

- docs/troubleshooting/migrate_cstor_pools.md
- docs/troubleshooting/migrate_cstor_volume.md
- docs/troubleshooting/pool_operations_hung.md
- docs/troubleshooting/troubleshooting.md
This PR adds a troubleshooting document to migrate/rebuild the cStor volumes from lost
pool to the new or existing cStor pool.
> chore(docs): add troubleshooting steps to migrate cStor volume from lost pool to new pool

- docs/quick.md
- docs/troubleshooting/migrate_cstor_volume.md
- docs/troubleshooting/rancher_prerequisite.md
- docs/troubleshooting/troubleshooting.md
This PR adds prerequisite steps to install cStor-CSI
on rancher based Kubernetes cluster.
> chore(docs): add prerequisite to install CStor-CSI on rancher based cluster

- pkg/controllers/cstorvolumeconfig/controller.go
- pkg/controllers/cstorvolumeconfig/deployment.go
**What This PR Does**:
This PR updates the cStor-volume manager deployment
with specified values on `CVC.Spec.Policy`.
**Current Behaviour**: 
- Currently when existing resource limits are removed
from CVC the changes are not propagated to the
corresponding volume-manager deployment.
> fix(reconciliation): update deployment with specified values in cvc policy

- pkg/webhook/cspc.go
- pkg/webhook/cspc_test.go
This PR fix the cStor admission server to perform
CRUD operations on CSPC when blockdevice has FS
type **zfs_member**. Why only "zfs_member" when
cStor pools are created fs type on the disk will
be shown as "zfs_member".
**NOTE**: This will be more helpful if users are
migrating from SPC based APIs to CSPC APIs.
**Sample Blockdevice Yaml with FS type**:
```sh
apiVersion: openebs.io/v1alpha1
kind: BlockDevice
metadata:
creationTimestamp: "2020-07-29T09:15:30Z"
finalizers:
- openebs.io/bd-protection
generation: 9
labels:
kubernetes.io/hostname: centos-worker-1
ndm.io/blockdevice-type: blockdevice
ndm.io/managed: "true"
name: blockdevice-0b068bf489941cdb4c5133e5d911467b
namespace: openebs
resourceVersion: "26696242"
selfLink: /apis/openebs.io/v1alpha1/namespaces/openebs/blockdevices/blockdevi …
```
> fix(admission server): allow CRUD operations on CSPC if disk has zfs filesystem

- build/pool-manager/Dockerfile
- build/pool-manager/entrypoint.sh
- pkg/controllers/cspi-controller/handler.go
- pkg/controllers/cspi-controller/handler_test.go
- pkg/controllers/cspi-controller/runner.go
This PR updates the CSPI status to **OFFLINE** whenever
cStor pool-manager container is terminated. Pod deletion, eviction,
scale down are a few scenarios that will cause the container
to terminate.
**NOTE**: Status will be not updated in case of aburupt
the shutdown of pods/nodes.
This PR fixes: #128 
> fix(status): update CSPI status when corresponding cStor pool-manager terminated

- go.mod
- go.sum
- pkg/webhook/cspc.go
- vendor/github.com/openebs/api/pkg/apis/types/types.go
- vendor/modules.txt
BD can be tagged in order to reserve it to be used later or by other storage
engine. If a tag is found in BD then it should not be used by cstor. This commit
adds a check for this. If a tag is found in BD and is used in CSPC for cStor
pool provisioning then the cStor webhook server will reject the request.
**NOTE:** This PR https://github.com/openebs/api/pull/62/files needs to be merged first and then a rebase will be required for the current PR.
> chore(validations): add check for BD tag presence

- pkg/version/util.go
This PR adds `1.12.0` & `2.0.0` as valid current versions to upgrade matrix for upgrade support from `1.12.0` and RC upgrades in `2.0.0`.
This PR fixes the issue: https://github.com/openebs/openebs/issues/3098
> chore(version): update upgrade matrix with valid current versions

- tests/cstorvolume/provisioing/provisioning_test.go
- tests/cstorvolume/provisioing/provisioning_utils.go
- tests/pkg/cstorvolumeconfig/cvcspecbuilder/specbuilder.go
- tests/pkg/k8sclient/cspc_util.go
- tests/pkg/k8sclient/cv_util.go
- tests/pkg/k8sclient/cvc_util.go
- tests/pkg/k8sclient/pvc_util.go
This PR adds covers the following integration test cases:
- Updating (includes adding and removing) resource requirements on CVC.
- Adding toleration on CVC.
- Adding priority class name on CVC.
- Update luworkers and queuedepth values on CVC.
- Updating CVC with a target node selector.
> feat(tests): add integration test cases for changing the policies on CVC dynamically

- tests/cstorvolume/provisioing/provisioning_test.go
- tests/cstorvolume/provisioing/provisioning_utils.go
- tests/pkg/cstorvolumeconfig/cvcspecbuilder/specbuilder.go
- tests/pkg/k8sclient/cspc_util.go
- tests/pkg/k8sclient/cv_util.go
- tests/pkg/k8sclient/cvc_util.go
- tests/pkg/k8sclient/cvr_util.go
- tests/pkg/k8sclient/pvc_util.go
This PR adds CStorVolume scaleup and scaledown integration tests.
It covers the following scenario
- Scaling up cStor volume.
-  Scaling down cStor volume.
-  Scaling up cStor volume when not enough pool are available. (-ve)
-  Scaleup in the same pool. (-ve)
-  Scaleup when already a scaleup operation is in progress.(-ve)
-  Scale down when already a scale down operation is in progress.(-ve)
**NOTE**: This PR needs to be merged after merging https://github.com/openebs/cstor-operators/pull/148
> feat(tests): add integration tests for scaleup and scaledown of CStorVolume

- deploy/crds/all_cstor_crds.yaml
- deploy/csi-operator.yaml
- go.mod
- go.sum
- vendor/github.com/openebs/api/pkg/apis/cstor/v1/cstorpoolinstance.go
- vendor/modules.txt
This PR does the following changes
- Updates the vendor files to point to the latest API changes
- Updates the CSPI CRD changes to intact with PR https://github.com/openebs/api/pull/63.
- Update the CSIDriver with Ephemeral `volumeLifecycleModes` (Just not to break the upgrade workflow)
> refact(vendor): sync with openebs apis changes

- tests/cspc/provisioning/provisioning_test.go
- tests/pkg/cspc/cspcspecbuilder/specbuilder.go
- tests/pkg/k8sclient/cspc_util.go
This PR adds tuneable tests that are passed via CSPC mentioned in https://github.com/openebs/cstor-operators/issues/111
Following is the output : 
```bash
Running Suite: CSPC Integration Tests
=====================================
Random Seed: 1596745849
Will run 15 of 15 specs
I0807 02:00:57.972153   11408 cache.go:57] Building CSPC Resource Cache...
CSPC stripe CSPC Pass resource and limit via CSPC 
creating the cspc,no error should be returned
/home/k8s/go_projects/src/openebs/cstor-operators/tests/cspc/provisioning/provisioning_test.go:422
•
------------------------------
CSPC stripe CSPC Pass resource and limit via CSPC 
Expected number of CSPI should be created
/home/k8s/go_projects/src/openebs/cstor-operators/tests/cspc/provisioning/provisioning_test.go:452
• [SLOW TEST:6.013 …
```
> test(cspc): add cspc tunables test

- pkg/server/cstorvolumeconfig/backup_endpoint.go
Changes:
- This PR fixes snapshot deletion during backup delete request.
Existing backup endpoint uses cstor-backup resource's namespace to fetch relevant cstorvolume resource for PV, to delete the snapshot. This will result into error since cstorvolume resource are created in operator namespace instead of application namespace.
Signed-off-by: mayank <mayank.patel@mayadata.io>
> fix(backup): fixing deletion of backup snapshot

- .github/workflows/go.yml
- .travis.yml
This commit is to change golang version from 1.13.6 to 1.14.7
Signed-off-by: ajeetrai707 <ajeetrai707@gmail.com>
> Bump golang version to 1.14.7

- pkg/controllers/cspc-controller/sync.go
This PR updates the cStorPoolInstance with the default
value of the ROThresholdLimit if user doesn't specify
ROThresholdLimit. The default value of ROThresholdLimit
is 85%. 
**NOTE**:
- This PR is to just display roThresholdLimit on CSPI resources(
It is already handled internally in CSPI controller).
> fix(roThreshold): update default roThresholdLimit to 85% during sync time

- Makefile
- pkg/controllers/cspc-controller/handler_test.go
- pkg/cspc/algorithm/select_node.go
- pkg/webhook/cspc.go
- tests/cstorvolume/provisioing/provisioning_utils.go
This PR creates claims for write cache raid groups
and wait till they get claimed before provisioning
the pools.
> fix(write cache): create claim for write cache raid group blockdevices

- go.mod
- go.sum
- pkg/controllers/cspc-controller/util/cspc_util_test.go
- pkg/controllers/cstorvolumeconfig/volume_operations_test.go
- pkg/cspc/algorithm/select_node.go
- pkg/cspc/algorithm/select_node_test.go
- pkg/snapshot/snapshottest/snapshot.go
- pkg/version/util.go
- pkg/volume-rpc/targetserver/config.go
- pkg/webhook/cspc.go
- pkg/webhook/cspc_operations.go
- pkg/webhook/cspc_operations_test.go
- pkg/zcmd/zfs/stats/stats.go
- tests/cstorvolume/provisioing/provisioning_utils.go
- vendor/github.com/openebs/api/pkg/apis/types/types.go
- vendor/modules.txt
This PR adds capability to specify allowed BD tags on CSPC via
annotations.
The annotation key is `cstor.openebs.io/allowed-bd-tags` and allowed value
is comma separated strings.
For example "fast,slow" is a possible value and in this case CSPC provisioner
will reject BDs that have a BD tag (`openebs.io/block-device-tag`) present on
it and the value is other than fast or slow.
> feat(cspc): add capability to specify allowed BD tags on CSPC

- pkg/version/util.go
This PR adds `2.1.0` to upgrade matrix for upgrading to custom images tags for `2.1.0`
> chore(upgrade): add valid current versions for 2.1.0 upgrades

- .github/workflows/go.yml
- .travis.yml
- Makefile
- build/cspc-operator/Dockerfile
- build/cstor-webhook/Dockerfile
- build/cvc-operator/Dockerfile
- build/cvc-operator/Dockerfile.arm64
- build/cvc-operator/entrypoint.sh
- build/pool-manager/Dockerfile
- build/pool-manager/entrypoint.sh
- build/volume-manager/Dockerfile
- build/volume-manager/Dockerfile.arm64
- build/volume-manager/entrypoint.sh
- go.mod
- go.sum
- pkg/controllers/cspc-controller/util/cspc_util_test.go
- pkg/controllers/cstorvolumeconfig/volume_operations_test.go
- pkg/cspc/algorithm/select_node.go
- pkg/cspc/algorithm/select_node_test.go
- pkg/snapshot/snapshottest/snapshot.go
- pkg/version/util.go
- pkg/volume-rpc/targetserver/config.go
- pkg/webhook/cspc.go
- pkg/webhook/cspc_operations.go
- pkg/webhook/cspc_operations_test.go
- pkg/zcmd/zfs/stats/stats.go
- tests/cstorvolume/provisioing/provisioning_utils.go
- vendor/github.com/openebs/api/pkg/apis/types/types.go
- vendor/modules.txt
This PR is a cherry-pick PR for the following PRs: 
https://github.com/openebs/cstor-operators/pull/169
The following two PRs were required to avoid rebase changes as license headers were added in go files: 
https://github.com/openebs/cstor-operators/pull/170
https://github.com/openebs/cstor-operators/pull/171
The following is bd-tag PR 
https://github.com/openebs/cstor-operators/pull/172
This cherry-pick required a rebase
> cherry_pick(goversion,license,bd-tag): cherry pick PRs  in 2.0.x branch

- pkg/controllers/cspc-controller/sync.go
- pkg/controllers/cstorvolumeconfig/controller.go
- pkg/snapshot/client.go
Fixed the typo in cstor operator logs. change namesapce into namespace
> fix(typo): Fixes typo in cstor cspc controller log messages

- deploy/crds/all_cstor_crds.yaml
- go.mod
- go.sum
- pkg/server/cstorvolumeconfig/backup_endpoint.go
- pkg/server/cstorvolumeconfig/backup_restore_helper.go
- pkg/server/cstorvolumeconfig/https_test.go
- pkg/server/cstorvolumeconfig/interface.go
- pkg/server/cstorvolumeconfig/restore_endpoint.go
- pkg/server/cstorvolumeconfig/v1_backup.go
- pkg/server/cstorvolumeconfig/v1alpha1_backup.go
- pkg/server/cstorvolumeconfig/v1alpha1_restore.go
- vendor/github.com/hashicorp/go-version/LICENSE
- vendor/github.com/hashicorp/go-version/README.md
- vendor/github.com/hashicorp/go-version/constraint.go
- vendor/github.com/hashicorp/go-version/go.mod
- vendor/github.com/hashicorp/go-version/version.go
- vendor/github.com/hashicorp/go-version/version_collection.go
- vendor/modules.txt
This PR does the following changes:
- Add support for the v1 version of cStor backup and restore at rest endpoint.
- Add backward compatibility to support v1alpha1 version of cStor backup and restore.
- Add unit test to verify both versions of cStor backup and restore.
- Add CStor backup and restore v1 version CRD's
- Remove CStor backup and restore v1alpha1 version of CRD's while installing. 
**If the changes in this PR are manually verified, list down the scenarios covered**:
- Create backup and restore backup using minio when all the pool-manager supports v1 version(both the crds are installed).
- Create backup and restore backup using minio when few of the pool-manager supports the v1 version and other supports the v1alpha1 version.
```sh
Restore v1alpha1 version
NAMESPACE   NAME …
```
> feat(backup & restore): add v1 support for backup and restore

- pkg/version/util.go
This PR adds 2.2.0 to the valid current version map to enable RC upgrades and custom image upgrades.
> chore(version): add 2.2.0 to upgrade matrix

- pkg/controllers/cspc-controller/handler_test.go
- pkg/controllers/cspc-controller/scale.go
- pkg/controllers/cspc-controller/sync.go
- pkg/cspc/algorithm/select_node.go
This PR adds support to move CStorPoolInstances to
different node when nodeSelector has been updated
with new node details.
Fixes https://github.com/openebs/openebs/issues/2396
**Changes Made**:
- Currently CSPC pool specs and CStorPoolInstance are
mapping using nodeSelectors but to support few scenarios
we should identify by making use of blockdevices in data raid
groups.
**Use Case**: This use case is to support following scenarios:
1. When node name changes upon reboots of node updating corresponding
node selector on CSPC will move the CStorPools to new node.
2. When existing node is replaced with new node in the cluster updating
corresponding node selector on CSPC should move the CStorPools to new node.
3. Scaling down the nodes in cluster to 0 and scaling back should work by
updating …
> feat(CSPC, nodeName changes): add suport to move the CStorPoolInstances to specified node

- pkg/server/cstorvolumeconfig/restore_endpoint.go
- pkg/server/cstorvolumeconfig/v1alpha1_restore.go
This PR fixes the issue to fetch the status of CStorRestore.
**Bug Description**:
Currently, CStorRestore resource is created using one of the label called
`cstorpoolinstance.openebs.io/name: <cspi_name>` but while
fetching the status of CStorRestore we are also fetching Pool-manager
status(Only in a case where CStorRestore status is not in `Done/Failed` state).
To fetch the pool manager we are using the CSPI name from non-existing
label(i.e `openebs.io/cstor-pool-instance`) of CStorRestore resource.
Due to that, there were partial failure errors in velero restore.
> fix(cstor restore): use relevant labels to fetch CSPI name

- pkg/server/cstorvolumeconfig/backup_endpoint.go
- pkg/server/cstorvolumeconfig/https_test.go
- pkg/server/cstorvolumeconfig/restore_endpoint.go
This PR creates backup and restore in `cstor.openebs.io/v1`
group if the pool is greater than or equal to 2.2.0.  
**Note** If CStor pool is in ci or dev version then backup and restore
will be created in `cstor.openebs.io` group. 
**Bug Description**: Currently code treats `2.2.0-RC1`(pool version)
is less than `2.2.0`(minimum openebs version to support v1 version
of backup and restore) due to this backup and restore is created in
`openebs.io` group but the backup/restore the controller will
understand `cstor.openebs.io` group and will not reconcile for resource.
Link: To test versions https://play.golang.org/p/KwHDhCi26Lx comparisons.
> fix(backup, restore): create backup and restore in cstor.openebs.io/v1 group

- Makefile
- pkg/controllers/cstorvolumeconfig/volume_operations.go
- pkg/controllers/replica-controller/controller.go
- pkg/controllers/replica-controller/handler.go
- pkg/volumereplica/volumereplica.go
Auto-setting of targetip on CVR if openebs.io/restore-completed is found
**Why is this PR required? What issue does it fix?**:
Currently, users have to set targetip on CVRs after restore. Corresponding change in https://github.com/openebs/velero-plugin/pull/131 will mark CVRs which needs to update the targetip. Changes in this PR will check the annotation and set the targetip.
**What this PR does?**:
Sets targetip on CVRs marked with openebs.io/restore-completed annotation.
**Does this PR require any upgrade changes?**:
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:
`make test` in velero-plugin repository with changes deployed.
**Any additional information for your reviewer?** : 
_Mention if this PR is part of any design or a continuation of …
> fix(restore): set targetip on CVRs after restore is completed

- Makefile.buildx.mk
Enabling more than two arch in the multi-arch builds
is resulting in increased build times as well as
intermittent failures in running the builds.
Limiting to two archs - amd64 and arm64 for now.
> refact(build): run only amd64 and arm64 builds

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile.buildx.mk
- build/cspc-operator/cspc-operator.Dockerfile
- build/cstor-webhook/cstor-webhook.Dockerfile
- build/cvc-operator/cvc-operator.Dockerfile
- build/pool-manager/pool-manager.Dockerfile
- build/volume-manager/volume-manager.Dockerfile
The RELEASE_TAG env set in the action is not propagated to the buildx container. This PR fixes the same.
This PR also removes the deprecated envs
> fix(build): propagate RELEASE_TAG to buildx container

- build/cspc-operator/cspc-operator.Dockerfile
- build/cvc-operator/cvc-operator.Dockerfile
- build/pool-manager/pool-manager.Dockerfile
- build/volume-manager/volume-manager.Dockerfile
The copy command in the buildx Dockerfiles is trying to copy the folder instead of the binaries which causes this error
```
Warning  Failed     4s (x4 over 51s)   kubelet, e2e1-node3  Error: failed to start container "cspc-operator": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/usr/local/bin/cspc-operator\": permission denied": unknown
```
> fix(build): copy binaries instead of folders

- docs/quick.md
Form 2.3.0 release onwards the ndm operator yaml is merged with the cstor-operator so we don't need to install the `openebs-operator` yaml for cstor installation.
> refact(docs): update the docs with latest yamls

- changelogs/unreleased/210-shubham14bajpai
- pkg/controllers/cspc-controller/sync.go
- pkg/version/util.go
**What this PR does:**
This PR fixes the cleanup issue of BDCs when the CSPIs doesn't get provisioned and CSPC is deleted. 
**How to replicate the scenario?**
Setup the cstor-operator yaml and check whether the BDs are active. Then scale down the ndm-operator deployment, this will prevent the BDCs from getting bound. If we delete the CPSC now the BDCs get the deletion timestamp but the cspc-operator does not remove the finalizer from the pending BDCs.
Tested the below code in the same scenario and the BDCs got cleaned up successfully.
> fix(cspc): cleanup pending bdcs on cspc deletion

- README.md
- _config.yml
- index.md
This PR adds helm chart install instructions to be displayed at the Github page. 
The page can be viewed at `openebs.github.io/cstor-operators` after the PRs 
#185 and #180 are merged.
> feat(gh-pages): add github page content for cstor helm charts

- .github/workflows/release.yml
Modify release workflow to run only when tags with `v` prefix are pushed.
This is required so that chart releases does not trigger a release workflow
> fix(action): fix release workflow to run only tags with `v` prefix

- deploy/csi-operator.yaml
- deploy/ndm-operator.yaml
- deploy/rbac.yaml
- deploy/snapshot_class.yaml
**What this PR does**:
- Bump k8s csi sidecar container image to latest stable  releases minimum kubernetes version to support 1.17
-  Remove the deprecated Cluster Driver Registrar container which is no longer required since the `CSIDriver` object instance should be created by CSI driver installer (or manually)
- Update the Snapshot specific CRDs to `V1` version
- Remove the `--provisioner` flag not required (not present)
in new version of csi-provisioner
- Added the `--default-fstype` flag required to be set new
csi-provisioner release
> chore(operator): bump k8s csi to latest stable container images

- docs/tutorial/volumes/snapshot.md
> chore(docs): update snapshot docs to include api version info

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/_helpers.tpl
- deploy/helm/charts/templates/cvc-operator-service.yaml
This PR makes the cvc operator service labels consistent with the operator yaml. This label is used by external operators like velero so consistency is necessary.
ref: https://github.com/openebs/charts/blob/ac87cc4dfb5bcb93b752d7947af30c143f3cadb8/cstor-operator.yaml#L4422
> fix(charts): make the cvc operator service labels consistent with operator

- deploy/crds/all_cstor_crds.yaml
- deploy/csi-operator.yaml
- deploy/cstor-operator.yaml
- Update upgradetask and cstorvolumeattachment crds to use
apiextensions.k8s.io/v1 version
-  Use k8s.gcr.io multi arch images for csi sidecars
> refact(crds): update upgradetask and cstorvolumeattachment to v1

- pkg/webhook/configuration.go
- pkg/webhook/namespace.go
- pkg/webhook/util.go
- pkg/webhook/webhook.go
- Add the openebs namespace delete validation checks
- Handle the `validatingwebhookconfiguration` garbage collection  issue due to invalid cross-namespace ownerReference checks introduced in k8s 1.20+
Refer:openebs/openebs#3338
from k8s 1.20+ onwards Cluster-scoped dependents can only specify cluster-scoped owners. In v1.20+, if a cluster-scoped dependent specifies a namespaced kind as an owner, it is treated as having an unresolveable owner reference, and is not able to be garbage collected.
In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. 
You can …
> fix(webhook): cleanup validatingwebhook config on openebs namespace deletion

- .github/auto_assign.yaml
- .github/workflows/auto_assign_prs.yml
Use a GitHub Action to automatically assign GitHub PRs to the author, as
well as add reviewers.
> feat(ci): auto-assign github PR reviewers and assignee using github-action

- .github/workflows/auto_assign_prs.yml
There was a typo in the config file name yml vs yaml after fixing the name action run correctly. verified the run here https://github.com/prateekpandey14/cstor-operators/pull/7/checks?check_run_id=1959361188
**Note:** auto assign action is failing here in PR since the action workflow files are not updated yet in master branch, once the PR merged, it will work fine for future pull requests
> fix(action): auto assign failure due to filename error

- docs/quick.md
- examples/cspc/cspc-single.yaml
- examples/cspc/cspc.yaml
Making the sample CSPC name the same across examples and quickstart, so that the default storageClass can be used out of the box no matter which sample CSPC a user decides to pick up.
Ref: [Slack thread](https://kubernetes.slack.com/archives/CUAKPFU78/p1616598454223100?thread_ts=1616433706.157900&cid=CUAKPFU78)
> chore(docs): making the sample CSPC names the same

- deploy/csi-operator.yaml
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/csi-driver.yaml
- pkg/version/util.go
With k8s v1.22 the v1beta1 for various resources will no longer be supported. This PR updates the csi driver api version to v1.
This PR also bumps the version matrix for v2.8.0
> chore(k8s): updated csi driver version to v1

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
The build.yml and pull_request.yml workflows will ignore pushes made to `docs/`, `deploy/helm/` and `changelogs/` directories. This will result in images not built for pushes made to above directories.
> chore(github-action): Avoid builds for pushes to helm chart, docs and changelog directories

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/cleanup-webhook.yaml
- deploy/helm/charts/values.yaml
This PR addresses the issue: https://github.com/openebs/openebs/issues/3383
The solution is based on looking into other projects with similar webhook related problems ref: https://github.com/Kong/gcp-marketplace/blob/main/GKE/Kuma/chart/templates/pre-delete-webhooks.yaml
> fix(helm): replace deprecated hyperkube image in pre-delete hook

- .github/workflows/auto_assign_prs.yml
- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- Makefile
- Makefile.buildx.mk
- pkg/version/util.go
This PR 
- replaces the buildx makefile with build and push action for multi repo push
- add quay.io repo to push images
- avoid build when release is created
> refact(actions): use build & push action instead of makefile

- pkg/snapshot/client.go
Signed-off-by: Nisarg Shah nisshah1499@gmail.com
Replaced fmt.Sprintf with net.JoinHostPort, because fmt.Sprintf will cause issues in IPv6. Best practice is to use net.JoinHostPort
Fixed  SemGrep complaint to use JoinHostPort instead of Sprintf for network address construction.
> JoinHostPort added

- build/volume-manager/Dockerfile
- build/volume-manager/volume-manager.Dockerfile
According to below document, ubuntu 16.04 has reached
it's EOL- https://wiki.ubuntu.com/Releases
Ref :#openebs/openebs/issues/3386
> chore(build): use ubuntu 18.04 as container base image

- pkg/controllers/cspc-controller/handler_test.go
- pkg/controllers/replica-controller/handler_test.go
- pkg/controllers/replica-controller/runner_test.go
- pkg/controllers/volume-mgmt/handler_test.go
- pkg/server/cstorvolumeconfig/backup_endpoint.go
- pkg/server/cstorvolumeconfig/v1alpha1_backup.go
- pkg/volume-rpc/client/api_test.go
Fixes:
- redundant breaks in switch case
- `x = append(y)` -> `x = y`
- unused funcs
- unused `err`
- `context.TODO()` instead of `nil`
Signed-off-by: arcolife <archit.py@gmail.com>
> static check fixes in {controllers, volume-rpc, server/cstorvolumeconfig}

- .gitpod.yml
- CONTRIBUTING.md
- README.md
Hi OpenEBS team! 👋
here is a PR that fully-automates the dev setup of cstor-operators with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/$project/$repo)
* Comes with all dependencies pre-installed (including Go, Docker, etc.)
* Runs `make all` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled cstor-operators CLI, and allows to easily edit & rebuild the code
I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).
Please let me know if I should …
> Added Gitpod config

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/_helpers.tpl
- deploy/helm/charts/templates/csi-controller.yaml
- deploy/helm/charts/templates/csi-node.yaml
- deploy/helm/charts/templates/priority-class.yaml
- deploy/helm/charts/values.yaml
Include storage engine name in priority class name to make sure CSI driver of different storage will have different priority class. This will resolve the issue of installing multiple storage engine using helm chart.
What will happen to older priority classes(upgrade scenario)?
=> Older priority classes will be deleted and CSI node and controller driver pod will be restarted with new priority classes.
> fix(helm chart): rename priority class name for CSI plugin (node and controller)

- cmd/volume-manager/app/commands.go
> Remove unused struct CmdSnaphotOptions

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/templates/cleanup-webhook.yaml
- deploy/helm/charts/values.yaml
This PR makes the cleanup pre delete hook job image configurable for air-gap setups
> refact(charts): make cleanup pre hook image configurable

- pkg/webhook/util.go
- pkg/webhook/util_test.go
This PR fixes the issue where the validatingwebhookconfiguration did not get updated the upgrading from 1.12.0 to latest versions.
```
failed to patch cspc cstor-cspc-disk-pool: Internal error occurred: failed calling webhook "admission-webhook.cstor.openebs.io": converting (v1.AdmissionReview) to (v1beta1.AdmissionReview): unknown conversion
```
> fix(webhook): fix version comparison of webhook resources

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/cleanup-webhook.yaml
Cleanup job fails if the validatingwebhookconfiguration is deleted beforehand. This stalls helm chart remove. Eventually leads to timeout. Fixed it with a OR clause.
> fix(cleanup-job): add OR clause to prevent job from failing

- .github/workflows/release.yml
This PR addresses the issue where a release workflow is triggered when a helm chart is released. The images pushed have tags with the name of the chart like [`cstor-2.10.1`](https://github.com/openebs/cstor-operators/actions/runs/950098654) in this case. We should avoid building images in such cases. The if condition added in the workflow prevents such workflows from executing.
> fix(actions): skip release workflow on helm release

- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/templates/snapshot-class.yaml
On some managed K8s clusters like OpenShift or GKE that ship with
their own default CSI Drivers, the controllers will end up creating
v1beta1 objects. An issue like the following was noticed when running
cstor charts on GKE 1.19.
```
unable to recognize "": no matches for kind "VolumeSnapshotClass" in
version "snapshot.storage.k8s.io/v1"
```
This commit uses the helm `.Capabilities` to check the version available
in the cluster and install the class accordingly. As the `.Capabilities`
might return false when using with template command, v1 is kept for false
(or default) case.
Manually verified on GKE with and without setting the flag as follows:
```
kiran_mova_mayadata_io@kmova-dev:charts$ helm install openebs-cstor . -n openebs --create-namespace --set openebsNDM.enabled =false 
NAME: …
```
> fix(helm): configure version for snapshot api

- pkg/controllers/volume-mgmt/volume/volume.go
This commit adds a new setting called **TCPUserTimeout** in istgt configuration.
The default value of TCPUserTimeout is configured to 120 seconds which means
the maximum amount of time in seconds that transmitted data may remain unacknowledged,
or buffered data may remain untransmitted(due to zero window size) before
TCP will forcibly close the corresponding connection and returns an error event
to application.
**Why is this change needed**:
The current implementation of cStor-istgt allows only one initiator
to consume a LUN(volume) at a time. When an initiator machine is
abruptly powered off the connection is no more active between client & target.
To know about client connection status istgt configures TCP_USER_TIMEOUT
to 120 seconds during login time.
**NOTE**:
TCP_USER_TIMEOUT will …
> fix(istgt config): add TCP User Timeout setting in istgt configuration

- pkg/controllers/volume-mgmt/volume/volume.go
This PR is cherry-pick of #354 
> cherry-pick(istgt config): add TCPUserTimeout setting in istgt configuration 

- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/README.md
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/chaosutil.j2
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/data_availability_check.yml
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/data_persistence.j2
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/run_e2e_test.yml
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/test.yml
- e2e-tests/experiments/infra-chaos/multiple_application_on_single_volume/test_vars.yml
- Verify the application that needs to perform chaos in Healthy and Running state.
- Dump data on the application to verify data availability post chaos. 
- Obtain the application deployment and scale the application deployment.
- Checking the Newly scaled pod is in `ContainerCreating` state and it's not mounted on the volume. And validated the Exsisting application pod status is Running. i.e: only one application pod should be running at a time
- PowerOff the node where the application pod is in Running state. And Validated the pod went to `ContainerCreating` state and the scaled pod is in `Running` state.
- Power on the node which shutdown during the chaos check the application pod is not login again. Verify the data availability …
> (E2E):Test case to validate the Multiple application request to connect on single cstor volume

- e2e-tests/chaoslib/openebs/inject_network_delay_tc.yml
- e2e-tests/chaoslib/openebs/inject_packet_loss_tc.yml
- e2e-tests/experiments/chaos/openebs_target_network_delay/chaosutil.j2
- e2e-tests/experiments/chaos/openebs_target_network_delay/test.yml
- e2e-tests/experiments/cstor-operator/cstor-operator-provisioner/test.yml
- e2e-tests/experiments/infra-chaos/drain_node/test.yml
- e2e-tests/experiments/infra-chaos/taint_node/test.yml
- Updated the e2e test case for target network delay. Included the chaos util to fix the failure in the test cases 
```
ansible-playbook 2.7.3
config file = None
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
executable location = /usr/local/bin/ansible-playbook
python version = 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
No config file found; using defaults
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected
PLAYBOOK: test.yml …
```
> refactor[e2e-tests]: Updated the e2e test for target network delay

- pkg/version/util.go
- pkg/version/util_test.go
This PR refactors the version validation for the jivaVolume CR during upgrades. As the versionDetails in the CR is only modified by either the upgrade job or the operator itself and is not user-facing we can switch to range-based validation. We will still maintain the upgrade matrix in upgrade repo to validate the job fields. This is eliminate the need to bump the upgrade matrix on each release.
> refact(version): use range instead of matrix for validation

- docs/tutorial/volumes/policy.md
This PR updates the policy documentation on usage of nodeSelector
to influence cStor target pod scheduling.
This PR fixes: https://github.com/openebs/cstor-csi/issues/144
> chore(doc): add documentation on usage of nodeSelector under Policy

- docs/troubleshooting/application_node_reboot.md
**What this PR does**?:
This PR adds troubleshooting doc when the application
pod remains in container creating state forever due to
mounting issues of cStor volume
It addresses the following issues via documentation:
- https://github.com/openebs/openebs/issues/3431
- https://github.com/openebs/cstor-operators/issues/213
> chore(doc): add troubleshooting doc when application remains in container creating state

- deploy/csi-operator.yaml
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/README.md
- deploy/helm/charts/values.yaml
Update the k8s csi sidecar images to support minimum k8s 1.20.x version.
- CSI Provisioner:
k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
- CSI Resizer:
k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
- CSI Node Driver Registrar
k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
**Note**: Keeping  the Snapshotter version as same as earlier , since the latest version only support the V1 snaphot apis , and  cloud k8s distribution, openshift etc does not supported the v1 snapshot APIs yet.
With current snapshotter 3.0.3 version  we have advantage that it will support both v1beta1/v1 apis, which will work in most of the cloud/openshift
> chore(operator): bump k8s csi sidecars images

- deploy/csi-operator.yaml
- deploy/helm/charts/Chart.yaml
- deploy/helm/charts/templates/priority-class.yaml
- deploy/helm/charts/values.yaml
use cstor in priority class name to avoid naming clash between different storage engines.
> update(yaml): update priority class name for csi driver
